
server.port: 8080

mybatis:
  type-aliases-package: org.wlyyy.itrs.dao
  type-handlers-package: org.wlyyy.itrs.mybatis
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

spring:
  datasource:
    driverClassName : com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/itrs?useUnicode:true&characterEncoding:utf-8&useSSL=true
    username : wlyyy
    password : yyylw
  redis:
    host: localhost

# server.servlet.session.cookie.domain: http://localhost*.com # Domain for the session cookie.
server.servlet.session.cookie.max-age: 300 # Maximum age of the session cookie. If a duration suffix is not specified, seconds will be used.
server.servlet.session.cookie.name: ITRS_SESSION_ID # Session cookie name.
server.servlet.session.persistent: true # Whether to persist session data between restarts.
server.servlet.session.timeout: 300 # Session timeout. If a duration suffix is not specified, seconds will be used.
server.servlet.session.tracking-modes: cookie # Session tracking modes (one or more of the following: "cookie", "url", "ssl").

# Skip null field at return json
spring.jackson.default-property-inclusion: NON_NULL

# activiti会对数据库中所有表进行更新操作。如果表不存在，则自动创建。
spring.activiti.database-schema: true

# 启动报错class path resource [processes/] cannot be resolved to URL because it does not exist
spring.activiti.check-process-definitions: false

# -==--==--=-==-=-=--==-=--==-=-=-
# custom
# -==--==--=-==-=-=--==-=--==-=-=-
web.crossorigin.domains: http://localhost:3000
