
spring:
  datasource:
    driverClassName : com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/itrs?useUnicode:true&characterEncoding:utf-8&useSSL=true
    username : root
    password : cao123
  redis:
    host: localhost

# -==--==--=-==-=-=--==-=--==-=-=-
# custom
# -==--==--=-==-=-=--==-=--==-=-=-
web.crossorigin.domains: http://localhost:3000
