mybatis:
    type-aliases-package: org.wlyyy.itrs.dao
    type-handlers-package: org.wlyyy.itrs.mybatis
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30

spring.datasource.driverClassName : com.mysql.jdbc.Driver
spring.datasource.url : jdbc:mysql://localhost:3306/itrs?useUnicode:true&characterEncoding:utf-8
spring.datasource.username : itrs_user
spring.datasource.password : cao123
