mybatis:
    type-aliases-package: org.wlyyy.itrs.dao
    type-handlers-package: org.wlyyy.itrs.mybatis
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30

spring:
  datasource:
    driverClassName : com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/itrs?useUnicode:true&characterEncoding:utf-8&useSSL=true
    username : root
    password : cao123
  redis:
    host: localhost

# activiti会对数据库中所有表进行更新操作。如果表不存在，则自动创建。
spring.activiti.database-schema: true

# 启动报错class path resource [processes/] cannot be resolved to URL because it does not exist
spring.activiti.check-process-definitions: false

# -==--==--=-==-=-=--==-=--==-=-=-
# custom
# -==--==--=-==-=-=--==-=--==-=-=-
web.crossorigin.domains: http://localhost:3000
# web.secirity.cookie.domain: http://localhost*.com
