= 需求接口

== 接口列表
- 分页复杂条件查询招聘需求
- 查询最新职位需求
- 根据招聘需求id查找招聘需求
- 发布需求
- 修改需求

=== 分页查询
本接口仅提供给前台页面使用。

==== URL
```
GET /demand/list?
```

==== 请求参数
[options="header"]
|======
| 字段 | 说明 | 类型 | 备注 | 是否必填
| pageNo | 页码 | Number | - | Y
| pageSize | 分页大小 | Number | - | Y
| publisherId | 发布者id | String | - | N
| positionType | 职位类别 | Number | 职位类别代码 | N
| jobName | 岗位名 | String | 具体的岗位完整名称 | N
| departmentId | 所属部门id | Number | - | N
| hrName | HR姓名 | String | 姓名匹配查询 | N
| totalStart | 招聘总人数最小值 | Number | - | N
| totalEnd | 招聘总人数最大值 | Number | - | N
| workingPlace | 工作地点 | String | 工作地点匹配 | N
| degreeRequest | 学位要求 | String | 匹配 | N
| gmtModifyStart | 需改时间起始 | String | yyyy-MM-dd HH:mm:ss | N
| gmtModifyEnd | 需改时间结束 | String | yyyy-MM-dd HH:mm:ss | N
|======

==== 返回示例
```json
{
    "success": true,
    "message": "Query success",
    "pageNo": 1,
    "pageSize": 10,
    "total": 20,
    "datas": [
        {
            "id": 123,
            "demandNo": "sdafhrgfgf433",
            "publisherId": 123,
            "publisherName": "publisherName001",
            "positionType": 211,
            "jobName": "position001",
            "departmentId": 121,
            "departmentName": "departmentName001",
            "hrName": "hrName001",
            "total": 3,
            "workingPlace": "workingPlace001",
            "degreeRequest": "degreeRequest001",
            "status": 1,
            "memo": "memo001",
            "gmtCreate": "gmtCreate001",
            "gmtModify": "gmtModify001"
        }
    ]
}
```

=== 查询最新职位需求
本接口仅提供给前台页面使用。

==== URL
```
GET /demand/get/id
```

==== 返回示例
```json
{
    "success": true,
    "message": "根据招聘需求id查找招聘需求成功",
    "data": {
        "id": 123,
        "demandNo": "sdafhrgfgf433",
        "publisherId": 123,
        "publisherName": "publisherName001",
        "positionType": 211,
        "jobName": "position001",
        "departmentId": 121,
        "departmentName": "departmentName001",
        "hrName": "hrName001",
        "total": 3,
        "workingPlace": "workingPlace001",
        "degreeRequest": "degreeRequest001",
        "status": 1,
        "memo": "memo001",
        "gmtCreate": "gmtCreate001",
        "gmtModify": "gmtModify001"
    }
}
```


=== 查询最新
本接口仅提供给前台页面使用。

==== URL
```
GET /demand/new?
```

==== 请求参数
[options="header"]
|======
| 字段 | 说明 | 类型 | 备注 | 是否必填
|======

==== 返回示例
```json
{
    "success": true,
    "message": "Query success",
    "pageNo": 1,
    "pageSize": 10,
    "total": 20,
    "datas": [
        {
            "id": 123,
            "demandNo": "sdafhrgfgf433",
            "publisherId": 123,
            "publisherName": "publisherName001",
            "positionType": 211,
            "jobName": "position001",
            "departmentId": 121,
            "departmentName": "departmentName001",
            "hrName": "hrName001",
            "total": 3,
            "workingPlace": "workingPlace001",
            "degreeRequest": "degreeRequest001",
            "status": 1,
            "memo": "memo001",
            "gmtCreate": "gmtCreate001",
            "gmtModify": "gmtModify001"
        }
    ]
}
```


=== 发布需求
本接口需要拥有HR角色才可以使用。

==== URL
```
POST /myProfile/demand?
```

==== 请求参数
[options="header"]
|======
| 字段 | 说明 | 类型 | 备注 | 是否必填
| positionType | 职位类别 | Number | 职位类别id | Y
| jobName | 岗位名 | String | 岗位详细名称 | Y
| total | 招聘总人数 | Number | - | Y
| workingPlace | 工作地点 | String | 全名 | Y
| degreeRequest | 学位要求 | String | 全名 | Y
| procKey | 流程定义key | String | 前台要选择用哪个流程 | Y
| memo | 备注 | String | - | Y

|======

==== 返回示例
```json
{
    "success": true,
    "message": "Create success"
}
```

=== 修改需求
本接口需要拥有HR角色才可以使用。

==== URL
```
PUT /myProfile/demand?
```

==== 请求参数
[options="header"]
|======
| 字段 | 说明 | 类型 | 备注 | 是否必填
| id | 需求id | Number | 职位类别id | Y
| positionType | 职位类别 | Number | 职位类别id | N
| jobName | 岗位名 | String | 岗位详细名称 | N
| total | 招聘总人数 | Number | - | N
| workingPlace | 工作地点 | String | 全名 | N
| degreeRequest | 学位要求 | String | 全名 | N
| status | 流程状态 | Number | 0已下线，1正常 | N
| memo | 备注 | String | - | N

|======

==== 返回示例
```json
{
    "success": true,
    "message": "Update success"
}
```
