= 流程相关接口

== 接口列表
- 员工推荐
- 根据需求id查询流程
- 查询需要面试的流程
- 查询该用户下的所有流程信息
- 查询当前用户的历史处理记录
- 处理流程任务

=== 推荐
本接口仅提供给前台页面使用，需要用户认证之后才可使用。

==== URL
```
POST /myProfile/flow/recommendTalent
```

==== 请求参数
[options="header"]
|======
| 字段 | 说明 | 类型 | 备注 | 是否必填
| demandId | 需求id | Number | - | Y
| name | 推荐人姓名 | String | - | Y
| sex | 性别 | Number | 0未知1男2女 | Y
| phoneNo | 手机号 | String | 中国手机号 | Y
| email | 电子邮箱 | String | - | Y
| graduateTime | 毕业时间 | String | yyyy-MM-dd | Y
| degree | 最高学位 | String | - | N
| workingPlace | 期望工作地点 | String | - | N
| memo | 备注 | String | - | N
| attachment | 附件标记 | String | - | N
|======

==== 返回示例
```json
{
    "success": true,
    "message": "员工推荐成功"
}
```

=== 根据需求id查询流程
查询某需求的所有推荐流程（hr）
若该用户不能对该流程进行操作，则taskId为-1，且操作为空

==== URL
```
GET /myProfile/flow/listApplyFlowHr?
```

==== 请求参数
[options="header"]
|======
| 字段 | 说明 | 类型 | 备注 | 是否必填
| demandId | 需求id | Number | - | Y
| pageNo | 页码 | Number | 默认1 | N
| pageSize | 页大小 | Number | 默认10 | N
|======

==== 返回示例
```json
{
    "success": true,
    "message": "查询展示层招聘流程信息表成功!",
    "datas": [
        {
            "id": 1,
            "demandId": 12,
            "demandNo": "11153",
            "taskId": "-1",
            "candidateId": 1,
            "candidateName": "翁羚晏",
            "candidateSex": null,
            "hopeWorkingPlace": null,
            "recommendId": 1,
            "recommendName": "realName",
            "currentFlowNode": "已结束",
            "currentDealer": "无",
            "currentResult": "放弃录用",
            "flowStatus": 2,
            "flowStatusName": "结束",
            "gmtCreate": "2018-04-29",
            "gmtModify": "2018-04-30",
            "operate": []
        },
        {
            "id": 2,
            "demandId": 12,
            "demandNo": "11153",
            "taskId": "-1",
            "candidateId": 2,
            "candidateName": "翁大宝",
            "candidateSex": null,
            "hopeWorkingPlace": null,
            "recommendId": 2,
            "recommendName": "realName",
            "currentFlowNode": "已结束",
            "currentDealer": "无",
            "currentResult": "电话面试未通过",
            "flowStatus": 2,
            "flowStatusName": "结束",
            "gmtCreate": "2018-04-29",
            "gmtModify": "2018-04-30",
            "operate": []
        }
    ],
    "pageNo": 1,
    "pageSize": 20,
    "total": 2
}
```


=== 查询需要面试的流程
展示该用户下的所有展示层招聘流程信息表（给面试官用）

==== URL
```
GET /myProfile/flow/listApplyFlowInterviewee?
```

==== 请求参数
[options="header"]
|======
| 字段 | 说明 | 类型 | 备注 | 是否必填
| pageNo | 页码 | Number | 默认1 | N
| pageSize | 页大小 | Number | 默认10 | N
|======

==== 返回示例
[options="header"]
|======
| 字段 | 说明 | 类型 | 备注 | 是否必填
| id | - | String | - | Y
| demandId | 需求id | String | - | Y
| demandNo | 需求编号 | String | - | Y
| taskId | 工作流引擎的TaskID | Number | 如果该用户不能操作该流程，返回-1 | Y
| candidateId | 被推荐人id | String | - | Y
| candidateName | 被推荐人姓名 | String | - | Y
| candidateSex | 被推荐人性别 | Number | - | Y
| hopeWorkingPlace | 期望工作地点 | String | - | Y
| recommendId | 推荐人id | String | - | Y
| recommendName | 推荐人姓名 | String | - | Y
| currentFlowNode | 当前流程节点 | String | 中文名 | Y
| currentDealer | 当前处理人 | String | 中文名 | Y
| currentResult | 当前流程结果 | String | 中文 | Y
| flowStatus | 流程状态 | Number | 1执行中，2异常，3已结束 | Y
| flowStatusName | 流程状态名 | String | 同上解释 | Y
| gmtCreate | - | String | yyyy-MM-dd HH:mm:ss | Y
| gmtModify | - | String | yyyy-MM-dd HH:mm:ss | Y
| operate | 操作 | List<String> | 中文操作 | Y
|======
```json
{
    "success": true,
    "message": "Create success"
}
```


=== 查询该用户下的所有流程信息
本接口仅提供给前台页面使用，需要用户认证后才可使用，
根据Session中的用户id查询该用户的所有推荐。

==== URL
```
GET /myProfile/flow/listApplyFlowRecommender?
```

==== 请求参数
[options="header"]
|======
| 字段 | 说明 | 类型 | 备注 | 是否必填
| pageNo | 页码 | Number | 默认1 | N
| pageSize | 页大小 | Number | 默认10 | N
|======

==== 返回示例
[options="header"]
|======
| 字段 | 说明 | 类型 | 备注 | 是否必填
| id | - | String | - | Y
| demandId | 需求id | String | - | Y
| demandNo | 需求编号 | String | - | Y
| taskId | 工作流引擎的TaskID | Number | 如果该用户不能操作该流程，返回-1 | Y
| candidateId | 被推荐人id | String | - | Y
| candidateName | 被推荐人姓名 | String | - | Y
| candidateSex | 被推荐人性别 | Number | - | Y
| hopeWorkingPlace | 期望工作地点 | String | - | Y
| recommendId | 推荐人id | String | - | Y
| recommendName | 推荐人姓名 | String | - | Y
| currentFlowNode | 当前流程节点 | String | 中文名 | Y
| currentDealer | 当前处理人 | String | 中文名 | Y
| currentResult | 当前流程结果 | String | 中文 | Y
| flowStatus | 流程状态 | Number | 1执行中，2异常，3已结束 | Y
| flowStatusName | 流程状态名 | String | 同上解释 | Y
| gmtCreate | - | String | yyyy-MM-dd HH:mm:ss | Y
| gmtModify | - | String | yyyy-MM-dd HH:mm:ss | Y
| operate | 操作 | List<String> | 中文操作 | Y
|======

```json
{
    "success": true,
    "message": "Query success",
    "pageNo": 1,
    "pageSize": 10,
    "total": 20,
    "datas": [
        {
            "id": 123,
            "demandId": 321,
            "demandNo": "2112213",
            "taskId": 123,
            "candidateId": 321,
            "candidateName": "动次打次",
            "candidateSex": 0,
            "hopeWorkingPlace": "杭州",
            "recommendId": 321,
            "recommendName": "推荐人姓名",
            "currentFlowNode": "当前流程节点",
            "currentDealer": "当前处理人",
            "currentResult": "当前流程结果",
            "flowStatus": 2,
            "flowStatusName": "异常",
            "gmtCreate": "yyyy-MM-dd HH:mm:ss",
            "gmtModify": "yyyy-MM-dd HH:mm:ss",
            "operate": [ "通过", "未通过" ],
        }
    ]
}
```


=== 查询当前用户的历史处理记录
查询当前用户的历史处理记录

==== URL
```
GET /myProfile/flow/listHistoricFlow?
```

==== 请求参数
[options="header"]
|======
| 字段 | 说明 | 类型 | 备注 | 是否必填
| pageNo | 页码 | Number | 默认1 | N
| pageSize | 页大小 | Number | 默认10 | N
|======

==== 返回示例
[options="header"]
|======
| 字段 | 说明 | 类型 | 备注 | 是否必填
| id | - | String | - | Y
| demandId | 需求id | String | - | Y
| demandNo | 需求编号 | String | - | Y
| taskId | 工作流引擎的TaskID | Number | 如果该用户不能操作该流程，返回-1 | Y
| candidateId | 被推荐人id | String | - | Y
| candidateName | 被推荐人姓名 | String | - | Y
| candidateSex | 被推荐人性别 | Number | - | Y
| hopeWorkingPlace | 期望工作地点 | String | - | Y
| recommendId | 推荐人id | String | - | Y
| recommendName | 推荐人姓名 | String | - | Y
| currentFlowNode | 当前流程节点 | String | 中文名 | Y
| currentDealer | 当前处理人 | String | 中文名 | Y
| currentResult | 当前流程结果 | String | 中文 | Y
| flowStatus | 流程状态 | Number | 1执行中，2异常，3已结束 | Y
| flowStatusName | 流程状态名 | String | 同上解释 | Y
| gmtCreate | - | String | yyyy-MM-dd HH:mm:ss | Y
| gmtModify | - | String | yyyy-MM-dd HH:mm:ss | Y
| operate | 操作 | List<String> | 中文操作 | Y
|======

```json
{
    "success": true,
    "message": "查询历史操作信息成功!",
    "datas": [
        {
            "taskId": "27503",
            "applyFlowId": 2,
            "demandNo": "11153",
            "node": "电话面试",
            "result": "电话面试未通过",
            "startTime": "2018-04-30 17:40:00",
            "endTime": "2018-04-30 17:45:14"
        },
        {
            "taskId": "20002",
            "applyFlowId": 1,
            "demandNo": "11153",
            "node": "二面",
            "result": "",
            "startTime": "2018-04-30 11:17:56",
            "endTime": "2018-04-30 12:22:13"
        }
    ],
    "pageNo": 1,
    "pageSize": 10,
    "total": 2
}
```

=== 处理流程任务
用户根据任务id处理任务，同时给出任务结果和下一任务执行人，并更新当前流程节点、当前处理人、当前结果和流程状态

要求传入outcome(必须), nextUserId(除最后一个节点外，必须，且只能有一个), result, taskId(必须), id(必须)

其中，outcome从operate中取；当指派面试官时，nextUserId为被指派的面试官id，当面试官给出结果时，nextUserId为发布该需求的hr id

id（对应applyFlowId字段）和applyFlowId从显示的列表中取即可；result 如面试官给出“电话面试不通过”

==== URL
```
POST /myProfile/flow/deal?
```

==== 请求参数
[options="header"]
|======
| 字段 | 说明 | 类型 | 备注 | 是否必填
| outcome | 连线名称（通过or不通过等） | String | 连线名称（通过or不通过等） | Y
| nextUserId | 下一任务的完成人 | String | 除最后一个节点外，必须，且只能有一个 | N
| result | 当前流程结果 | String | 中文结果 | Y
| taskId | 任务id | String | 必须 | Y
| id | 招聘流程id | Number | 对应applyFlowId | Y
|======

==== 返回示例

```json
{
    "success": true,
    "message": "完成任务成功!"
}
```

